substitutions:
  id_prefix: aq_mood_c3_kitchen
  name: Air Quality MoodLight 
  node_name: mista-aq-mood-c3-wall
  led_brightness: '0.20' # 0.0 to 1.0 argb led brightness on trurn in via touch long press
  #VOC limits
  voc_good_min: '100'
  voc_moderate_min: '200'
  voc_poor_min: '300'
  voc_unhealthy_min: '400'
  #PM (2.5) Limits
  pm_good_min: '25'
  pm_moderate_min: '50'
  pm_poor_min: '100'
  pm_unhealthy_min: '250'
  #CO2 limits
  co2_good_min: '600'
  co2_moderate_min: '800'
  co2_poor_min: '1000'
  co2_unhealthy_min: '1600'
  #Nox limits
  nox_good_min: '30'
  nox_moderate_min: '100'
  nox_poor_min: '200'
  nox_unhealthy_min: '300'
  #text and icon colors for aqis (total, pm, voc,co2,nox)
  color_excellent: 'C0EBA6'
  color_good: 'C0EBA6'
  color_moderate: 'FDFD00'
  color_poor: 'FF0000'
  color_unhealthy: 'FF0000'

  #PIN CFG C3 - use those to build for c3!
  pin_sda: 'GPIO06'
  pin_scl: 'GPIO07'
  pin_clk: 'GPIO08'
  pin_mosi: 'GPIO10'
  pin_reset: 'GPIO20'
  pin_cs: 'GPIO05'
  pin_dc: 'GPIO09'
  pin_backlight: 'GPIO04'
  pin_argb: 'GPIO03'
  pin_btn: 'GPIO02'


# check for your settings, or comment to dissable wifi/home assistant support!  
packages:
  wifi: !include src/aq-mood-home-assistant.yaml

# This loads the aq mood implementation
<<: !include src/aq-mood-base-c3.yaml